import DBSubnetGroup_ from './dbSubnetGroup';
import DBInstance_ from './dbInstance';
import DBSecurityGroup_ from './dbSecurityGroup';
import DBClusterParameterGroup_ from './dbClusterParameterGroup';
import DBSecurityGroupIngress_ from './dbSecurityGroupIngress';
import DBCluster_ from './dbCluster';
import OptionGroup_ from './optionGroup';
import DBParameterGroup_ from './dbParameterGroup';
import EventSubscription_ from './eventSubscription';
export declare namespace RDS {
    const DBSubnetGroup: typeof DBSubnetGroup_;
    const DBInstance: typeof DBInstance_;
    const DBSecurityGroup: typeof DBSecurityGroup_;
    const DBClusterParameterGroup: typeof DBClusterParameterGroup_;
    const DBSecurityGroupIngress: typeof DBSecurityGroupIngress_;
    const DBCluster: typeof DBCluster_;
    const OptionGroup: typeof OptionGroup_;
    const DBParameterGroup: typeof DBParameterGroup_;
    const EventSubscription: typeof EventSubscription_;
    type DBSubnetGroup = DBSubnetGroup_;
    type DBInstance = DBInstance_;
    type DBSecurityGroup = DBSecurityGroup_;
    type DBClusterParameterGroup = DBClusterParameterGroup_;
    type DBSecurityGroupIngress = DBSecurityGroupIngress_;
    type DBCluster = DBCluster_;
    type OptionGroup = OptionGroup_;
    type DBParameterGroup = DBParameterGroup_;
    type EventSubscription = EventSubscription_;
}
