import DBSecurityGroupIngress_ from './dbSecurityGroupIngress';
import DBCluster_ from './dbCluster';
import DBSubnetGroup_ from './dbSubnetGroup';
import OptionGroup_ from './optionGroup';
import DBParameterGroup_ from './dbParameterGroup';
import EventSubscription_ from './eventSubscription';
import DBInstance_ from './dbInstance';
import DBSecurityGroup_ from './dbSecurityGroup';
import DBClusterParameterGroup_ from './dbClusterParameterGroup';
export declare namespace RDS {
    const DBSecurityGroupIngress: typeof DBSecurityGroupIngress_;
    const DBCluster: typeof DBCluster_;
    const DBSubnetGroup: typeof DBSubnetGroup_;
    const OptionGroup: typeof OptionGroup_;
    const DBParameterGroup: typeof DBParameterGroup_;
    const EventSubscription: typeof EventSubscription_;
    const DBInstance: typeof DBInstance_;
    const DBSecurityGroup: typeof DBSecurityGroup_;
    const DBClusterParameterGroup: typeof DBClusterParameterGroup_;
    type DBSecurityGroupIngress = DBSecurityGroupIngress_;
    type DBCluster = DBCluster_;
    type DBSubnetGroup = DBSubnetGroup_;
    type OptionGroup = OptionGroup_;
    type DBParameterGroup = DBParameterGroup_;
    type EventSubscription = EventSubscription_;
    type DBInstance = DBInstance_;
    type DBSecurityGroup = DBSecurityGroup_;
    type DBClusterParameterGroup = DBClusterParameterGroup_;
}
