/* Generated from https://d3teyb21fexa9r.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json, version 1.11.0 */
   
import ElasticBeanstalk from './elasticBeanstalk'
import ElasticBeanstalkConfigurationTemplate from './elasticBeanstalk/configurationTemplate'
import ElasticBeanstalkApplication from './elasticBeanstalk/application'
import ElasticBeanstalkEnvironment from './elasticBeanstalk/environment'
import ElasticBeanstalkApplicationVersion from './elasticBeanstalk/applicationVersion'
import EC2 from './ec2'
import EC2RouteTable from './ec2/routeTable'
import EC2PlacementGroup from './ec2/placementGroup'
import EC2VPCPeeringConnection from './ec2/vpcPeeringConnection'
import EC2NetworkAclEntry from './ec2/networkAclEntry'
import EC2InternetGateway from './ec2/internetGateway'
import EC2Volume from './ec2/volume'
import EC2SpotFleet from './ec2/spotFleet'
import EC2VPNConnectionRoute from './ec2/vpnConnectionRoute'
import EC2NetworkInterfacePermission from './ec2/networkInterfacePermission'
import EC2EIP from './ec2/eip'
import EC2SecurityGroupIngress from './ec2/securityGroupIngress'
import EC2SubnetRouteTableAssociation from './ec2/subnetRouteTableAssociation'
import EC2Route from './ec2/route'
import EC2FlowLog from './ec2/flowLog'
import EC2SecurityGroupEgress from './ec2/securityGroupEgress'
import EC2NetworkInterface from './ec2/networkInterface'
import EC2SubnetNetworkAclAssociation from './ec2/subnetNetworkAclAssociation'
import EC2SubnetCidrBlock from './ec2/subnetCidrBlock'
import EC2NatGateway from './ec2/natGateway'
import EC2SecurityGroup from './ec2/securityGroup'
import EC2Subnet from './ec2/subnet'
import EC2VPC from './ec2/vpc'
import EC2Instance from './ec2/instance'
import EC2DHCPOptions from './ec2/dhcpOptions'
import EC2NetworkAcl from './ec2/networkAcl'
import EC2VPNGatewayRoutePropagation from './ec2/vpnGatewayRoutePropagation'
import EC2EgressOnlyInternetGateway from './ec2/egressOnlyInternetGateway'
import EC2NetworkInterfaceAttachment from './ec2/networkInterfaceAttachment'
import EC2CustomerGateway from './ec2/customerGateway'
import EC2TrunkInterfaceAssociation from './ec2/trunkInterfaceAssociation'
import EC2VolumeAttachment from './ec2/volumeAttachment'
import EC2Host from './ec2/host'
import EC2EIPAssociation from './ec2/eipAssociation'
import EC2VPNGateway from './ec2/vpnGateway'
import EC2VPCEndpoint from './ec2/vpcEndpoint'
import EC2VPCGatewayAttachment from './ec2/vpcGatewayAttachment'
import EC2VPNConnection from './ec2/vpnConnection'
import EC2VPCCidrBlock from './ec2/vpcCidrBlock'
import EC2VPCDHCPOptionsAssociation from './ec2/vpcdhcpOptionsAssociation'
import Cognito from './cognito'
import CognitoIdentityPoolRoleAttachment from './cognito/identityPoolRoleAttachment'
import CognitoUserPoolGroup from './cognito/userPoolGroup'
import CognitoIdentityPool from './cognito/identityPool'
import CognitoUserPoolUser from './cognito/userPoolUser'
import CognitoUserPool from './cognito/userPool'
import CognitoUserPoolClient from './cognito/userPoolClient'
import CognitoUserPoolUserToGroupAttachment from './cognito/userPoolUserToGroupAttachment'
import Events from './events'
import EventsRule from './events/rule'
import WAF from './waf'
import WAFIPSet from './waf/ipSet'
import WAFSizeConstraintSet from './waf/sizeConstraintSet'
import WAFRule from './waf/rule'
import WAFByteMatchSet from './waf/byteMatchSet'
import WAFSqlInjectionMatchSet from './waf/sqlInjectionMatchSet'
import WAFWebACL from './waf/webAcl'
import WAFXssMatchSet from './waf/xssMatchSet'
import IAM from './iam'
import IAMGroup from './iam/group'
import IAMPolicy from './iam/policy'
import IAMRole from './iam/role'
import IAMUserToGroupAddition from './iam/userToGroupAddition'
import IAMInstanceProfile from './iam/instanceProfile'
import IAMAccessKey from './iam/accessKey'
import IAMUser from './iam/user'
import IAMManagedPolicy from './iam/managedPolicy'
import CodePipeline from './codePipeline'
import CodePipelineCustomActionType from './codePipeline/customActionType'
import CodePipelinePipeline from './codePipeline/pipeline'
import Elasticsearch from './elasticsearch'
import ElasticsearchDomain from './elasticsearch/domain'
import WAFRegional from './wafRegional'
import WAFRegionalSizeConstraintSet from './wafRegional/sizeConstraintSet'
import WAFRegionalSqlInjectionMatchSet from './wafRegional/sqlInjectionMatchSet'
import WAFRegionalXssMatchSet from './wafRegional/xssMatchSet'
import WAFRegionalByteMatchSet from './wafRegional/byteMatchSet'
import WAFRegionalWebACLAssociation from './wafRegional/webAclAssociation'
import WAFRegionalWebACL from './wafRegional/webAcl'
import WAFRegionalRule from './wafRegional/rule'
import WAFRegionalIPSet from './wafRegional/ipSet'
import ApiGateway from './apiGateway'
import ApiGatewayRequestValidator from './apiGateway/requestValidator'
import ApiGatewayDeployment from './apiGateway/deployment'
import ApiGatewayAuthorizer from './apiGateway/authorizer'
import ApiGatewayDomainName from './apiGateway/domainName'
import ApiGatewayDocumentationPart from './apiGateway/documentationPart'
import ApiGatewayApiKey from './apiGateway/apiKey'
import ApiGatewayModel from './apiGateway/model'
import ApiGatewayResource from './apiGateway/resource'
import ApiGatewayAccount from './apiGateway/account'
import ApiGatewayRestApi from './apiGateway/restApi'
import ApiGatewayUsagePlan from './apiGateway/usagePlan'
import ApiGatewayBasePathMapping from './apiGateway/basePathMapping'
import ApiGatewayStage from './apiGateway/stage'
import ApiGatewayGatewayResponse from './apiGateway/gatewayResponse'
import ApiGatewayClientCertificate from './apiGateway/clientCertificate'
import ApiGatewayMethod from './apiGateway/method'
import ApiGatewayDocumentationVersion from './apiGateway/documentationVersion'
import ApiGatewayUsagePlanKey from './apiGateway/usagePlanKey'
import EMR from './emr'
import EMRInstanceFleetConfig from './emr/instanceFleetConfig'
import EMRCluster from './emr/cluster'
import EMRInstanceGroupConfig from './emr/instanceGroupConfig'
import EMRStep from './emr/step'
import EMRSecurityConfiguration from './emr/securityConfiguration'
import WorkSpaces from './workSpaces'
import WorkSpacesWorkspace from './workSpaces/workspace'
import RDS from './rds'
import RDSDBSecurityGroupIngress from './rds/dbSecurityGroupIngress'
import RDSDBCluster from './rds/dbCluster'
import RDSDBSubnetGroup from './rds/dbSubnetGroup'
import RDSOptionGroup from './rds/optionGroup'
import RDSDBParameterGroup from './rds/dbParameterGroup'
import RDSEventSubscription from './rds/eventSubscription'
import RDSDBInstance from './rds/dbInstance'
import RDSDBSecurityGroup from './rds/dbSecurityGroup'
import RDSDBClusterParameterGroup from './rds/dbClusterParameterGroup'
import Logs from './logs'
import LogsLogGroup from './logs/logGroup'
import LogsMetricFilter from './logs/metricFilter'
import LogsLogStream from './logs/logStream'
import LogsSubscriptionFilter from './logs/subscriptionFilter'
import LogsDestination from './logs/destination'
import Kinesis from './kinesis'
import KinesisStream from './kinesis/stream'
import AutoScaling from './autoScaling'
import AutoScalingLaunchConfiguration from './autoScaling/launchConfiguration'
import AutoScalingLifecycleHook from './autoScaling/lifecycleHook'
import AutoScalingScalingPolicy from './autoScaling/scalingPolicy'
import AutoScalingAutoScalingGroup from './autoScaling/autoScalingGroup'
import AutoScalingScheduledAction from './autoScaling/scheduledAction'
import SQS from './sqs'
import SQSQueue from './sqs/queue'
import SQSQueuePolicy from './sqs/queuePolicy'
import Route53 from './route53'
import Route53RecordSet from './route53/recordSet'
import Route53HostedZone from './route53/hostedZone'
import Route53RecordSetGroup from './route53/recordSetGroup'
import Route53HealthCheck from './route53/healthCheck'
import CloudWatch from './cloudWatch'
import CloudWatchDashboard from './cloudWatch/dashboard'
import CloudWatchAlarm from './cloudWatch/alarm'
import ECS from './ecs'
import ECSCluster from './ecs/cluster'
import ECSService from './ecs/service'
import ECSTaskDefinition from './ecs/taskDefinition'
import ElasticLoadBalancingV2 from './elasticLoadBalancingV2'
import ElasticLoadBalancingV2ListenerCertificate from './elasticLoadBalancingV2/listenerCertificate'
import ElasticLoadBalancingV2LoadBalancer from './elasticLoadBalancingV2/loadBalancer'
import ElasticLoadBalancingV2Listener from './elasticLoadBalancingV2/listener'
import ElasticLoadBalancingV2ListenerRule from './elasticLoadBalancingV2/listenerRule'
import ElasticLoadBalancingV2TargetGroup from './elasticLoadBalancingV2/targetGroup'
import StepFunctions from './stepFunctions'
import StepFunctionsActivity from './stepFunctions/activity'
import StepFunctionsStateMachine from './stepFunctions/stateMachine'
import KinesisAnalytics from './kinesisAnalytics'
import KinesisAnalyticsApplicationOutput from './kinesisAnalytics/applicationOutput'
import KinesisAnalyticsApplicationReferenceDataSource from './kinesisAnalytics/applicationReferenceDataSource'
import KinesisAnalyticsApplication from './kinesisAnalytics/application'
import OpsWorks from './opsWorks'
import OpsWorksVolume from './opsWorks/volume'
import OpsWorksApp from './opsWorks/app'
import OpsWorksLayer from './opsWorks/layer'
import OpsWorksStack from './opsWorks/stack'
import OpsWorksElasticLoadBalancerAttachment from './opsWorks/elasticLoadBalancerAttachment'
import OpsWorksInstance from './opsWorks/instance'
import OpsWorksUserProfile from './opsWorks/userProfile'
import CloudFront from './cloudFront'
import CloudFrontStreamingDistribution from './cloudFront/streamingDistribution'
import CloudFrontDistribution from './cloudFront/distribution'
import CloudFrontCloudFrontOriginAccessIdentity from './cloudFront/cloudFrontOriginAccessIdentity'
import GameLift from './gameLift'
import GameLiftAlias from './gameLift/alias'
import GameLiftBuild from './gameLift/build'
import GameLiftFleet from './gameLift/fleet'
import DirectoryService from './directoryService'
import DirectoryServiceMicrosoftAD from './directoryService/microsoftAd'
import DirectoryServiceSimpleAD from './directoryService/simpleAd'
import SNS from './sns'
import SNSSubscription from './sns/subscription'
import SNSTopic from './sns/topic'
import SNSTopicPolicy from './sns/topicPolicy'
import EFS from './efs'
import EFSMountTarget from './efs/mountTarget'
import EFSFileSystem from './efs/fileSystem'
import SSM from './ssm'
import SSMDocument from './ssm/document'
import SSMPatchBaseline from './ssm/patchBaseline'
import SSMParameter from './ssm/parameter'
import SSMAssociation from './ssm/association'
import SSMMaintenanceWindowTask from './ssm/maintenanceWindowTask'
import Config from './config'
import ConfigDeliveryChannel from './config/deliveryChannel'
import ConfigConfigurationRecorder from './config/configurationRecorder'
import ConfigConfigRule from './config/configRule'
import KMS from './kms'
import KMSKey from './kms/key'
import KMSAlias from './kms/alias'
import Redshift from './redshift'
import RedshiftCluster from './redshift/cluster'
import RedshiftClusterParameterGroup from './redshift/clusterParameterGroup'
import RedshiftClusterSecurityGroupIngress from './redshift/clusterSecurityGroupIngress'
import RedshiftClusterSubnetGroup from './redshift/clusterSubnetGroup'
import RedshiftClusterSecurityGroup from './redshift/clusterSecurityGroup'
import Lambda from './lambda'
import LambdaEventSourceMapping from './lambda/eventSourceMapping'
import LambdaAlias from './lambda/alias'
import LambdaFunction from './lambda/function'
import LambdaVersion from './lambda/version'
import LambdaPermission from './lambda/permission'
import CertificateManager from './certificateManager'
import CertificateManagerCertificate from './certificateManager/certificate'
import Batch from './batch'
import BatchJobDefinition from './batch/jobDefinition'
import BatchJobQueue from './batch/jobQueue'
import BatchComputeEnvironment from './batch/computeEnvironment'
import ElasticLoadBalancing from './elasticLoadBalancing'
import ElasticLoadBalancingLoadBalancer from './elasticLoadBalancing/loadBalancer'
import IoT from './iot'
import IoTThing from './iot/thing'
import IoTPolicy from './iot/policy'
import IoTTopicRule from './iot/topicRule'
import IoTPolicyPrincipalAttachment from './iot/policyPrincipalAttachment'
import IoTThingPrincipalAttachment from './iot/thingPrincipalAttachment'
import IoTCertificate from './iot/certificate'
import DMS from './dms'
import DMSCertificate from './dms/certificate'
import DMSReplicationSubnetGroup from './dms/replicationSubnetGroup'
import DMSEventSubscription from './dms/eventSubscription'
import DMSEndpoint from './dms/endpoint'
import DMSReplicationTask from './dms/replicationTask'
import DMSReplicationInstance from './dms/replicationInstance'
import ElastiCache from './elastiCache'
import ElastiCacheSecurityGroup from './elastiCache/securityGroup'
import ElastiCacheSubnetGroup from './elastiCache/subnetGroup'
import ElastiCacheSecurityGroupIngress from './elastiCache/securityGroupIngress'
import ElastiCacheReplicationGroup from './elastiCache/replicationGroup'
import ElastiCacheParameterGroup from './elastiCache/parameterGroup'
import ElastiCacheCacheCluster from './elastiCache/cacheCluster'
import CodeDeploy from './codeDeploy'
import CodeDeployDeploymentGroup from './codeDeploy/deploymentGroup'
import CodeDeployDeploymentConfig from './codeDeploy/deploymentConfig'
import CodeDeployApplication from './codeDeploy/application'
import CodeBuild from './codeBuild'
import CodeBuildProject from './codeBuild/project'
import DAX from './dax'
import DAXSubnetGroup from './dax/subnetGroup'
import DAXParameterGroup from './dax/parameterGroup'
import DAXCluster from './dax/cluster'
import DataPipeline from './dataPipeline'
import DataPipelinePipeline from './dataPipeline/pipeline'
import CloudTrail from './cloudTrail'
import CloudTrailTrail from './cloudTrail/trail'
import CloudFormation from './cloudFormation'
import CloudFormationWaitCondition from './cloudFormation/waitCondition'
import CloudFormationStack from './cloudFormation/stack'
import CloudFormationWaitConditionHandle from './cloudFormation/waitConditionHandle'
import CloudFormationCustomResource from './cloudFormation/customResource'
import ApplicationAutoScaling from './applicationAutoScaling'
import ApplicationAutoScalingScalingPolicy from './applicationAutoScaling/scalingPolicy'
import ApplicationAutoScalingScalableTarget from './applicationAutoScaling/scalableTarget'
import CodeCommit from './codeCommit'
import CodeCommitRepository from './codeCommit/repository'
import S3 from './s3'
import S3Bucket from './s3/bucket'
import S3BucketPolicy from './s3/bucketPolicy'
import KinesisFirehose from './kinesisFirehose'
import KinesisFirehoseDeliveryStream from './kinesisFirehose/deliveryStream'
import SDB from './sdb'
import SDBDomain from './sdb/domain'
import ECR from './ecr'
import ECRRepository from './ecr/repository'
import DynamoDB from './dynamoDb'
import DynamoDBTable from './dynamoDb/table'
import Athena from './athena'
import AthenaNamedQuery from './athena/namedQuery' 

export default {
  ElasticBeanstalk,
  EC2,
  Cognito,
  Events,
  WAF,
  IAM,
  CodePipeline,
  Elasticsearch,
  WAFRegional,
  ApiGateway,
  EMR,
  WorkSpaces,
  RDS,
  Logs,
  Kinesis,
  AutoScaling,
  SQS,
  Route53,
  CloudWatch,
  ECS,
  ElasticLoadBalancingV2,
  StepFunctions,
  KinesisAnalytics,
  OpsWorks,
  CloudFront,
  GameLift,
  DirectoryService,
  SNS,
  EFS,
  SSM,
  Config,
  KMS,
  Redshift,
  Lambda,
  CertificateManager,
  Batch,
  ElasticLoadBalancing,
  IoT,
  DMS,
  ElastiCache,
  CodeDeploy,
  CodeBuild,
  DAX,
  DataPipeline,
  CloudTrail,
  CloudFormation,
  ApplicationAutoScaling,
  CodeCommit,
  S3,
  KinesisFirehose,
  SDB,
  ECR,
  DynamoDB,
  Athena
}
