import Route_ from './route';
import Integration_ from './integration';
import Stage_ from './stage';
import Deployment_ from './deployment';
import Model_ from './model';
import Authorizer_ from './authorizer';
import Api_ from './api';
import RouteResponse_ from './routeResponse';
import IntegrationResponse_ from './integrationResponse';
export declare namespace ApiGatewayV2 {
    const Route: typeof Route_;
    const Integration: typeof Integration_;
    const Stage: typeof Stage_;
    const Deployment: typeof Deployment_;
    const Model: typeof Model_;
    const Authorizer: typeof Authorizer_;
    const Api: typeof Api_;
    const RouteResponse: typeof RouteResponse_;
    const IntegrationResponse: typeof IntegrationResponse_;
    type Route = Route_;
    type Integration = Integration_;
    type Stage = Stage_;
    type Deployment = Deployment_;
    type Model = Model_;
    type Authorizer = Authorizer_;
    type Api = Api_;
    type RouteResponse = RouteResponse_;
    type IntegrationResponse = IntegrationResponse_;
}
