import Route from './route';
import Integration from './integration';
import Stage from './stage';
import Deployment from './deployment';
import Model from './model';
import Authorizer from './authorizer';
import Api from './api';
import RouteResponse from './routeResponse';
import IntegrationResponse from './integrationResponse';
declare const _default: {
    Route: typeof Route;
    Integration: typeof Integration;
    Stage: typeof Stage;
    Deployment: typeof Deployment;
    Model: typeof Model;
    Authorizer: typeof Authorizer;
    Api: typeof Api;
    RouteResponse: typeof RouteResponse;
    IntegrationResponse: typeof IntegrationResponse;
};
export default _default;
