import Association_ from './association';
import Document_ from './document';
import MaintenanceWindow_ from './maintenanceWindow';
import MaintenanceWindowTarget_ from './maintenanceWindowTarget';
import MaintenanceWindowTask_ from './maintenanceWindowTask';
import Parameter_ from './parameter';
import PatchBaseline_ from './patchBaseline';
import ResourceDataSync_ from './resourceDataSync';
import ResourcePolicy_ from './resourcePolicy';
export declare namespace SSM {
    const Association: typeof Association_;
    const Document: typeof Document_;
    const MaintenanceWindow: typeof MaintenanceWindow_;
    const MaintenanceWindowTarget: typeof MaintenanceWindowTarget_;
    const MaintenanceWindowTask: typeof MaintenanceWindowTask_;
    const Parameter: typeof Parameter_;
    const PatchBaseline: typeof PatchBaseline_;
    const ResourceDataSync: typeof ResourceDataSync_;
    const ResourcePolicy: typeof ResourcePolicy_;
    type Association = Association_;
    type Document = Document_;
    type MaintenanceWindow = MaintenanceWindow_;
    type MaintenanceWindowTarget = MaintenanceWindowTarget_;
    type MaintenanceWindowTask = MaintenanceWindowTask_;
    type Parameter = Parameter_;
    type PatchBaseline = PatchBaseline_;
    type ResourceDataSync = ResourceDataSync_;
    type ResourcePolicy = ResourcePolicy_;
}
