import CacheCluster_ from './cacheCluster';
import GlobalReplicationGroup_ from './globalReplicationGroup';
import ParameterGroup_ from './parameterGroup';
import ReplicationGroup_ from './replicationGroup';
import SecurityGroup_ from './securityGroup';
import SecurityGroupIngress_ from './securityGroupIngress';
import SubnetGroup_ from './subnetGroup';
import User_ from './user';
import UserGroup_ from './userGroup';
export declare namespace ElastiCache {
    const CacheCluster: typeof CacheCluster_;
    const GlobalReplicationGroup: typeof GlobalReplicationGroup_;
    const ParameterGroup: typeof ParameterGroup_;
    const ReplicationGroup: typeof ReplicationGroup_;
    const SecurityGroup: typeof SecurityGroup_;
    const SecurityGroupIngress: typeof SecurityGroupIngress_;
    const SubnetGroup: typeof SubnetGroup_;
    const User: typeof User_;
    const UserGroup: typeof UserGroup_;
    type CacheCluster = CacheCluster_;
    type GlobalReplicationGroup = GlobalReplicationGroup_;
    type ParameterGroup = ParameterGroup_;
    type ReplicationGroup = ReplicationGroup_;
    type SecurityGroup = SecurityGroup_;
    type SecurityGroupIngress = SecurityGroupIngress_;
    type SubnetGroup = SubnetGroup_;
    type User = User_;
    type UserGroup = UserGroup_;
}
