import Group from './group';
import ConnectorDefinition from './connectorDefinition';
import ConnectorDefinitionVersion from './connectorDefinitionVersion';
import FunctionDefinition from './functionDefinition';
import SubscriptionDefinitionVersion from './subscriptionDefinitionVersion';
import CoreDefinitionVersion from './coreDefinitionVersion';
import DeviceDefinition from './deviceDefinition';
import LoggerDefinition from './loggerDefinition';
import CoreDefinition from './coreDefinition';
import DeviceDefinitionVersion from './deviceDefinitionVersion';
import SubscriptionDefinition from './subscriptionDefinition';
import ResourceDefinitionVersion from './resourceDefinitionVersion';
import LoggerDefinitionVersion from './loggerDefinitionVersion';
import FunctionDefinitionVersion from './functionDefinitionVersion';
import GroupVersion from './groupVersion';
import ResourceDefinition from './resourceDefinition';
declare const _default: {
    Group: typeof Group;
    ConnectorDefinition: typeof ConnectorDefinition;
    ConnectorDefinitionVersion: typeof ConnectorDefinitionVersion;
    FunctionDefinition: typeof FunctionDefinition;
    SubscriptionDefinitionVersion: typeof SubscriptionDefinitionVersion;
    CoreDefinitionVersion: typeof CoreDefinitionVersion;
    DeviceDefinition: typeof DeviceDefinition;
    LoggerDefinition: typeof LoggerDefinition;
    CoreDefinition: typeof CoreDefinition;
    DeviceDefinitionVersion: typeof DeviceDefinitionVersion;
    SubscriptionDefinition: typeof SubscriptionDefinition;
    ResourceDefinitionVersion: typeof ResourceDefinitionVersion;
    LoggerDefinitionVersion: typeof LoggerDefinitionVersion;
    FunctionDefinitionVersion: typeof FunctionDefinitionVersion;
    GroupVersion: typeof GroupVersion;
    ResourceDefinition: typeof ResourceDefinition;
};
export default _default;
