import Analysis_ from './analysis';
import Dashboard_ from './dashboard';
import DataSet_ from './dataSet';
import DataSource_ from './dataSource';
import RefreshSchedule_ from './refreshSchedule';
import Template_ from './template';
import Theme_ from './theme';
import VPCConnection_ from './vpcConnection';
import Topic_ from './topic';
export declare namespace QuickSight {
    const Analysis: typeof Analysis_;
    const Dashboard: typeof Dashboard_;
    const DataSet: typeof DataSet_;
    const DataSource: typeof DataSource_;
    const RefreshSchedule: typeof RefreshSchedule_;
    const Template: typeof Template_;
    const Theme: typeof Theme_;
    const VPCConnection: typeof VPCConnection_;
    const Topic: typeof Topic_;
    type Analysis = Analysis_;
    type Dashboard = Dashboard_;
    type DataSet = DataSet_;
    type DataSource = DataSource_;
    type RefreshSchedule = RefreshSchedule_;
    type Template = Template_;
    type Theme = Theme_;
    type VPCConnection = VPCConnection_;
    type Topic = Topic_;
}
