import Alias_ from './alias';
import Build_ from './build';
import Fleet_ from './fleet';
import GameServerGroup_ from './gameServerGroup';
import GameSessionQueue_ from './gameSessionQueue';
import Location_ from './location';
import MatchmakingConfiguration_ from './matchmakingConfiguration';
import MatchmakingRuleSet_ from './matchmakingRuleSet';
import Script_ from './script';
export declare namespace GameLift {
    const Alias: typeof Alias_;
    const Build: typeof Build_;
    const Fleet: typeof Fleet_;
    const GameServerGroup: typeof GameServerGroup_;
    const GameSessionQueue: typeof GameSessionQueue_;
    const Location: typeof Location_;
    const MatchmakingConfiguration: typeof MatchmakingConfiguration_;
    const MatchmakingRuleSet: typeof MatchmakingRuleSet_;
    const Script: typeof Script_;
    type Alias = Alias_;
    type Build = Build_;
    type Fleet = Fleet_;
    type GameServerGroup = GameServerGroup_;
    type GameSessionQueue = GameSessionQueue_;
    type Location = Location_;
    type MatchmakingConfiguration = MatchmakingConfiguration_;
    type MatchmakingRuleSet = MatchmakingRuleSet_;
    type Script = Script_;
}
