import SDC from './sdc';
export { SDC };
import ACMPCA from './acmpca';
export { ACMPCA };
import APS from './aps';
export { APS };
import AccessAnalyzer from './accessAnalyzer';
export { AccessAnalyzer };
import AmazonMQ from './amazonMq';
export { AmazonMQ };
import Amplify from './amplify';
export { Amplify };
import AmplifyUIBuilder from './amplifyUiBuilder';
export { AmplifyUIBuilder };
import ApiGateway from './apiGateway';
export { ApiGateway };
import ApiGatewayV2 from './apiGatewayV2';
export { ApiGatewayV2 };
import AppConfig from './appConfig';
export { AppConfig };
import AppFlow from './appFlow';
export { AppFlow };
import AppIntegrations from './appIntegrations';
export { AppIntegrations };
import AppMesh from './appMesh';
export { AppMesh };
import AppRunner from './appRunner';
export { AppRunner };
import AppStream from './appStream';
export { AppStream };
import AppSync from './appSync';
export { AppSync };
import ApplicationAutoScaling from './applicationAutoScaling';
export { ApplicationAutoScaling };
import ApplicationInsights from './applicationInsights';
export { ApplicationInsights };
import Athena from './athena';
export { Athena };
import AuditManager from './auditManager';
export { AuditManager };
import AutoScaling from './autoScaling';
export { AutoScaling };
import AutoScalingPlans from './autoScalingPlans';
export { AutoScalingPlans };
import Backup from './backup';
export { Backup };
import BackupGateway from './backupGateway';
export { BackupGateway };
import Batch from './batch';
export { Batch };
import Budgets from './budgets';
export { Budgets };
import CE from './ce';
export { CE };
import Cassandra from './cassandra';
export { Cassandra };
import CertificateManager from './certificateManager';
export { CertificateManager };
import Chatbot from './chatbot';
export { Chatbot };
import CleanRooms from './cleanRooms';
export { CleanRooms };
import Cloud9 from './cloud9';
export { Cloud9 };
import CloudFormation from './cloudFormation';
export { CloudFormation };
import CloudFront from './cloudFront';
export { CloudFront };
import CloudTrail from './cloudTrail';
export { CloudTrail };
import CloudWatch from './cloudWatch';
export { CloudWatch };
import CodeArtifact from './codeArtifact';
export { CodeArtifact };
import CodeBuild from './codeBuild';
export { CodeBuild };
import CodeCommit from './codeCommit';
export { CodeCommit };
import CodeDeploy from './codeDeploy';
export { CodeDeploy };
import CodeGuruProfiler from './codeGuruProfiler';
export { CodeGuruProfiler };
import CodeGuruReviewer from './codeGuruReviewer';
export { CodeGuruReviewer };
import CodePipeline from './codePipeline';
export { CodePipeline };
import CodeStar from './codeStar';
export { CodeStar };
import CodeStarConnections from './codeStarConnections';
export { CodeStarConnections };
import CodeStarNotifications from './codeStarNotifications';
export { CodeStarNotifications };
import Cognito from './cognito';
export { Cognito };
import Comprehend from './comprehend';
export { Comprehend };
import Config from './config';
export { Config };
import Connect from './connect';
export { Connect };
import ControlTower from './controlTower';
export { ControlTower };
import CustomerProfiles from './customerProfiles';
export { CustomerProfiles };
import DAX from './dax';
export { DAX };
import DLM from './dlm';
export { DLM };
import DMS from './dms';
export { DMS };
import DataBrew from './dataBrew';
export { DataBrew };
import DataPipeline from './dataPipeline';
export { DataPipeline };
import DataSync from './dataSync';
export { DataSync };
import Detective from './detective';
export { Detective };
import DevOpsGuru from './devOpsGuru';
export { DevOpsGuru };
import DirectoryService from './directoryService';
export { DirectoryService };
import DocDB from './docDb';
export { DocDB };
import DocDBElastic from './docDbElastic';
export { DocDBElastic };
import DynamoDB from './dynamoDb';
export { DynamoDB };
import EC2 from './ec2';
export { EC2 };
import ECR from './ecr';
export { ECR };
import ECS from './ecs';
export { ECS };
import EFS from './efs';
export { EFS };
import EKS from './eks';
export { EKS };
import EMR from './emr';
export { EMR };
import EMRContainers from './emrContainers';
export { EMRContainers };
import EMRServerless from './emrServerless';
export { EMRServerless };
import ElastiCache from './elastiCache';
export { ElastiCache };
import ElasticBeanstalk from './elasticBeanstalk';
export { ElasticBeanstalk };
import ElasticLoadBalancing from './elasticLoadBalancing';
export { ElasticLoadBalancing };
import ElasticLoadBalancingV2 from './elasticLoadBalancingV2';
export { ElasticLoadBalancingV2 };
import Elasticsearch from './elasticsearch';
export { Elasticsearch };
import EntityResolution from './entityResolution';
export { EntityResolution };
import EventSchemas from './eventSchemas';
export { EventSchemas };
import Events from './events';
export { Events };
import Evidently from './evidently';
export { Evidently };
import FIS from './fis';
export { FIS };
import FMS from './fms';
export { FMS };
import FSx from './fSx';
export { FSx };
import Forecast from './forecast';
export { Forecast };
import GameLift from './gameLift';
export { GameLift };
import GlobalAccelerator from './globalAccelerator';
export { GlobalAccelerator };
import Glue from './glue';
export { Glue };
import Grafana from './grafana';
export { Grafana };
import Greengrass from './greengrass';
export { Greengrass };
import GreengrassV2 from './greengrassV2';
export { GreengrassV2 };
import GuardDuty from './guardDuty';
export { GuardDuty };
import IAM from './iam';
export { IAM };
import IVS from './ivs';
export { IVS };
import IVSChat from './ivsChat';
export { IVSChat };
import IdentityStore from './identityStore';
export { IdentityStore };
import ImageBuilder from './imageBuilder';
export { ImageBuilder };
import Inspector from './inspector';
export { Inspector };
import InspectorV2 from './inspectorV2';
export { InspectorV2 };
import InternetMonitor from './internetMonitor';
export { InternetMonitor };
import IoT1Click from './ioT1Click';
export { IoT1Click };
import IoT from './iot';
export { IoT };
import IoTAnalytics from './ioTAnalytics';
export { IoTAnalytics };
import IoTCoreDeviceAdvisor from './ioTCoreDeviceAdvisor';
export { IoTCoreDeviceAdvisor };
import IoTEvents from './ioTEvents';
export { IoTEvents };
import IoTFleetHub from './ioTFleetHub';
export { IoTFleetHub };
import IoTSiteWise from './ioTSiteWise';
export { IoTSiteWise };
import IoTThingsGraph from './ioTThingsGraph';
export { IoTThingsGraph };
import IoTTwinMaker from './ioTTwinMaker';
export { IoTTwinMaker };
import IoTWireless from './ioTWireless';
export { IoTWireless };
import KMS from './kms';
export { KMS };
import KafkaConnect from './kafkaConnect';
export { KafkaConnect };
import Kendra from './kendra';
export { Kendra };
import KendraRanking from './kendraRanking';
export { KendraRanking };
import Kinesis from './kinesis';
export { Kinesis };
import KinesisAnalytics from './kinesisAnalytics';
export { KinesisAnalytics };
import KinesisAnalyticsV2 from './kinesisAnalyticsV2';
export { KinesisAnalyticsV2 };
import KinesisFirehose from './kinesisFirehose';
export { KinesisFirehose };
import KinesisVideo from './kinesisVideo';
export { KinesisVideo };
import LakeFormation from './lakeFormation';
export { LakeFormation };
import Lambda from './lambda';
export { Lambda };
import Lex from './lex';
export { Lex };
import LicenseManager from './licenseManager';
export { LicenseManager };
import Lightsail from './lightsail';
export { Lightsail };
import Location from './location';
export { Location };
import Logs from './logs';
export { Logs };
import LookoutMetrics from './lookoutMetrics';
export { LookoutMetrics };
import LookoutVision from './lookoutVision';
export { LookoutVision };
import M2 from './m2';
export { M2 };
import MSK from './msk';
export { MSK };
import MWAA from './mwaa';
export { MWAA };
import Macie from './macie';
export { Macie };
import ManagedBlockchain from './managedBlockchain';
export { ManagedBlockchain };
import MediaConnect from './mediaConnect';
export { MediaConnect };
import MediaConvert from './mediaConvert';
export { MediaConvert };
import MediaLive from './mediaLive';
export { MediaLive };
import MediaPackage from './mediaPackage';
export { MediaPackage };
import MediaPackageV2 from './mediaPackageV2';
export { MediaPackageV2 };
import MediaStore from './mediaStore';
export { MediaStore };
import MediaTailor from './mediaTailor';
export { MediaTailor };
import MemoryDB from './memoryDb';
export { MemoryDB };
import Neptune from './neptune';
export { Neptune };
import NetworkFirewall from './networkFirewall';
export { NetworkFirewall };
import NetworkManager from './networkManager';
export { NetworkManager };
import NimbleStudio from './nimbleStudio';
export { NimbleStudio };
import OSIS from './osis';
export { OSIS };
import Oam from './oam';
export { Oam };
import OpenSearchServerless from './openSearchServerless';
export { OpenSearchServerless };
import OpenSearchService from './openSearchService';
export { OpenSearchService };
import OpsWorks from './opsWorks';
export { OpsWorks };
import OpsWorksCM from './opsWorksCm';
export { OpsWorksCM };
import Organizations from './organizations';
export { Organizations };
import PCAConnectorAD from './pcaConnectorAd';
export { PCAConnectorAD };
import Personalize from './personalize';
export { Personalize };
import Pinpoint from './pinpoint';
export { Pinpoint };
import Pipes from './pipes';
export { Pipes };
import Proton from './proton';
export { Proton };
import QLDB from './qldb';
export { QLDB };
import QuickSight from './quickSight';
export { QuickSight };
import RAM from './ram';
export { RAM };
import RDS from './rds';
export { RDS };
import RUM from './rum';
export { RUM };
import Redshift from './redshift';
export { Redshift };
import RedshiftServerless from './redshiftServerless';
export { RedshiftServerless };
import RefactorSpaces from './refactorSpaces';
export { RefactorSpaces };
import Rekognition from './rekognition';
export { Rekognition };
import ResilienceHub from './resilienceHub';
export { ResilienceHub };
import ResourceExplorer2 from './resourceExplorer2';
export { ResourceExplorer2 };
import ResourceGroups from './resourceGroups';
export { ResourceGroups };
import RoboMaker from './roboMaker';
export { RoboMaker };
import RolesAnywhere from './rolesAnywhere';
export { RolesAnywhere };
import Route53 from './route53';
export { Route53 };
import Route53Resolver from './route53Resolver';
export { Route53Resolver };
import S3 from './s3';
export { S3 };
import S3ObjectLambda from './s3ObjectLambda';
export { S3ObjectLambda };
import S3Outposts from './s3Outposts';
export { S3Outposts };
import SDB from './sdb';
export { SDB };
import SES from './ses';
export { SES };
import SNS from './sns';
export { SNS };
import SQS from './sqs';
export { SQS };
import SSM from './ssm';
export { SSM };
import SSMContacts from './ssmContacts';
export { SSMContacts };
import SSMIncidents from './ssmIncidents';
export { SSMIncidents };
import SSO from './sso';
export { SSO };
import SageMaker from './sageMaker';
export { SageMaker };
import Scheduler from './scheduler';
export { Scheduler };
import SecretsManager from './secretsManager';
export { SecretsManager };
import SecurityHub from './securityHub';
export { SecurityHub };
import ServiceCatalog from './serviceCatalog';
export { ServiceCatalog };
import ServiceCatalogAppRegistry from './serviceCatalogAppRegistry';
export { ServiceCatalogAppRegistry };
import ServiceDiscovery from './serviceDiscovery';
export { ServiceDiscovery };
import Shield from './shield';
export { Shield };
import Signer from './signer';
export { Signer };
import StepFunctions from './stepFunctions';
export { StepFunctions };
import SupportApp from './supportApp';
export { SupportApp };
import Synthetics from './synthetics';
export { Synthetics };
import SystemsManagerSAP from './systemsManagerSap';
export { SystemsManagerSAP };
import Timestream from './timestream';
export { Timestream };
import Transfer from './transfer';
export { Transfer };
import VerifiedPermissions from './verifiedPermissions';
export { VerifiedPermissions };
import VoiceID from './voiceId';
export { VoiceID };
import VpcLattice from './vpcLattice';
export { VpcLattice };
import WAF from './waf';
export { WAF };
import WAFRegional from './wafRegional';
export { WAFRegional };
import WAFv2 from './waFv2';
export { WAFv2 };
import Wisdom from './wisdom';
export { Wisdom };
import WorkSpaces from './workSpaces';
export { WorkSpaces };
import WorkSpacesWeb from './workSpacesWeb';
export { WorkSpacesWeb };
import XRay from './xRay';
export { XRay };
import ASK from './ask';
export { ASK };
import GroundStation from './groundStation';
export { GroundStation };
import LookoutEquipment from './lookoutEquipment';
export { LookoutEquipment };
import CodeTest from './codeTest';
export { CodeTest };
import HealthLake from './healthLake';
export { HealthLake };
import PinpointEmail from './pinpointEmail';
export { PinpointEmail };
import FraudDetector from './fraudDetector';
export { FraudDetector };
import GammaDilithium from './gammaDilithium';
export { GammaDilithium };
import Omics from './omics';
export { Omics };
import Panorama from './panorama';
export { Panorama };
import SimSpaceWeaver from './simSpaceWeaver';
export { SimSpaceWeaver };
import ConnectCampaigns from './connectCampaigns';
export { ConnectCampaigns };
import HealthImaging from './healthImaging';
export { HealthImaging };
import FinSpace from './finSpace';
export { FinSpace };
import IoTFleetWise from './ioTFleetWise';
export { IoTFleetWise };
import BillingConductor from './billingConductor';
export { BillingConductor };
import CUR from './cur';
export { CUR };
import Route53RecoveryControl from './route53RecoveryControl';
export { Route53RecoveryControl };
import Route53RecoveryReadiness from './route53RecoveryReadiness';
export { Route53RecoveryReadiness };
import DeviceFarm from './deviceFarm';
export { DeviceFarm };
declare const _default: {
    SDC: typeof SDC;
    ACMPCA: typeof ACMPCA;
    APS: typeof APS;
    AccessAnalyzer: typeof AccessAnalyzer;
    AmazonMQ: typeof AmazonMQ;
    Amplify: typeof Amplify;
    AmplifyUIBuilder: typeof AmplifyUIBuilder;
    ApiGateway: typeof ApiGateway;
    ApiGatewayV2: typeof ApiGatewayV2;
    AppConfig: typeof AppConfig;
    AppFlow: typeof AppFlow;
    AppIntegrations: typeof AppIntegrations;
    AppMesh: typeof AppMesh;
    AppRunner: typeof AppRunner;
    AppStream: typeof AppStream;
    AppSync: typeof AppSync;
    ApplicationAutoScaling: typeof ApplicationAutoScaling;
    ApplicationInsights: typeof ApplicationInsights;
    Athena: typeof Athena;
    AuditManager: typeof AuditManager;
    AutoScaling: typeof AutoScaling;
    AutoScalingPlans: typeof AutoScalingPlans;
    Backup: typeof Backup;
    BackupGateway: typeof BackupGateway;
    Batch: typeof Batch;
    Budgets: typeof Budgets;
    CE: typeof CE;
    Cassandra: typeof Cassandra;
    CertificateManager: typeof CertificateManager;
    Chatbot: typeof Chatbot;
    CleanRooms: typeof CleanRooms;
    Cloud9: typeof Cloud9;
    CloudFormation: typeof CloudFormation;
    CloudFront: typeof CloudFront;
    CloudTrail: typeof CloudTrail;
    CloudWatch: typeof CloudWatch;
    CodeArtifact: typeof CodeArtifact;
    CodeBuild: typeof CodeBuild;
    CodeCommit: typeof CodeCommit;
    CodeDeploy: typeof CodeDeploy;
    CodeGuruProfiler: typeof CodeGuruProfiler;
    CodeGuruReviewer: typeof CodeGuruReviewer;
    CodePipeline: typeof CodePipeline;
    CodeStar: typeof CodeStar;
    CodeStarConnections: typeof CodeStarConnections;
    CodeStarNotifications: typeof CodeStarNotifications;
    Cognito: typeof Cognito;
    Comprehend: typeof Comprehend;
    Config: typeof Config;
    Connect: typeof Connect;
    ControlTower: typeof ControlTower;
    CustomerProfiles: typeof CustomerProfiles;
    DAX: typeof DAX;
    DLM: typeof DLM;
    DMS: typeof DMS;
    DataBrew: typeof DataBrew;
    DataPipeline: typeof DataPipeline;
    DataSync: typeof DataSync;
    Detective: typeof Detective;
    DevOpsGuru: typeof DevOpsGuru;
    DirectoryService: typeof DirectoryService;
    DocDB: typeof DocDB;
    DocDBElastic: typeof DocDBElastic;
    DynamoDB: typeof DynamoDB;
    EC2: typeof EC2;
    ECR: typeof ECR;
    ECS: typeof ECS;
    EFS: typeof EFS;
    EKS: typeof EKS;
    EMR: typeof EMR;
    EMRContainers: typeof EMRContainers;
    EMRServerless: typeof EMRServerless;
    ElastiCache: typeof ElastiCache;
    ElasticBeanstalk: typeof ElasticBeanstalk;
    ElasticLoadBalancing: typeof ElasticLoadBalancing;
    ElasticLoadBalancingV2: typeof ElasticLoadBalancingV2;
    Elasticsearch: typeof Elasticsearch;
    EntityResolution: typeof EntityResolution;
    EventSchemas: typeof EventSchemas;
    Events: typeof Events;
    Evidently: typeof Evidently;
    FIS: typeof FIS;
    FMS: typeof FMS;
    FSx: typeof FSx;
    Forecast: typeof Forecast;
    GameLift: typeof GameLift;
    GlobalAccelerator: typeof GlobalAccelerator;
    Glue: typeof Glue;
    Grafana: typeof Grafana;
    Greengrass: typeof Greengrass;
    GreengrassV2: typeof GreengrassV2;
    GuardDuty: typeof GuardDuty;
    IAM: typeof IAM;
    IVS: typeof IVS;
    IVSChat: typeof IVSChat;
    IdentityStore: typeof IdentityStore;
    ImageBuilder: typeof ImageBuilder;
    Inspector: typeof Inspector;
    InspectorV2: typeof InspectorV2;
    InternetMonitor: typeof InternetMonitor;
    IoT1Click: typeof IoT1Click;
    IoT: typeof IoT;
    IoTAnalytics: typeof IoTAnalytics;
    IoTCoreDeviceAdvisor: typeof IoTCoreDeviceAdvisor;
    IoTEvents: typeof IoTEvents;
    IoTFleetHub: typeof IoTFleetHub;
    IoTSiteWise: typeof IoTSiteWise;
    IoTThingsGraph: typeof IoTThingsGraph;
    IoTTwinMaker: typeof IoTTwinMaker;
    IoTWireless: typeof IoTWireless;
    KMS: typeof KMS;
    KafkaConnect: typeof KafkaConnect;
    Kendra: typeof Kendra;
    KendraRanking: typeof KendraRanking;
    Kinesis: typeof Kinesis;
    KinesisAnalytics: typeof KinesisAnalytics;
    KinesisAnalyticsV2: typeof KinesisAnalyticsV2;
    KinesisFirehose: typeof KinesisFirehose;
    KinesisVideo: typeof KinesisVideo;
    LakeFormation: typeof LakeFormation;
    Lambda: typeof Lambda;
    Lex: typeof Lex;
    LicenseManager: typeof LicenseManager;
    Lightsail: typeof Lightsail;
    Location: typeof Location;
    Logs: typeof Logs;
    LookoutMetrics: typeof LookoutMetrics;
    LookoutVision: typeof LookoutVision;
    M2: typeof M2;
    MSK: typeof MSK;
    MWAA: typeof MWAA;
    Macie: typeof Macie;
    ManagedBlockchain: typeof ManagedBlockchain;
    MediaConnect: typeof MediaConnect;
    MediaConvert: typeof MediaConvert;
    MediaLive: typeof MediaLive;
    MediaPackage: typeof MediaPackage;
    MediaPackageV2: typeof MediaPackageV2;
    MediaStore: typeof MediaStore;
    MediaTailor: typeof MediaTailor;
    MemoryDB: typeof MemoryDB;
    Neptune: typeof Neptune;
    NetworkFirewall: typeof NetworkFirewall;
    NetworkManager: typeof NetworkManager;
    NimbleStudio: typeof NimbleStudio;
    OSIS: typeof OSIS;
    Oam: typeof Oam;
    OpenSearchServerless: typeof OpenSearchServerless;
    OpenSearchService: typeof OpenSearchService;
    OpsWorks: typeof OpsWorks;
    OpsWorksCM: typeof OpsWorksCM;
    Organizations: typeof Organizations;
    PCAConnectorAD: typeof PCAConnectorAD;
    Personalize: typeof Personalize;
    Pinpoint: typeof Pinpoint;
    Pipes: typeof Pipes;
    Proton: typeof Proton;
    QLDB: typeof QLDB;
    QuickSight: typeof QuickSight;
    RAM: typeof RAM;
    RDS: typeof RDS;
    RUM: typeof RUM;
    Redshift: typeof Redshift;
    RedshiftServerless: typeof RedshiftServerless;
    RefactorSpaces: typeof RefactorSpaces;
    Rekognition: typeof Rekognition;
    ResilienceHub: typeof ResilienceHub;
    ResourceExplorer2: typeof ResourceExplorer2;
    ResourceGroups: typeof ResourceGroups;
    RoboMaker: typeof RoboMaker;
    RolesAnywhere: typeof RolesAnywhere;
    Route53: typeof Route53;
    Route53Resolver: typeof Route53Resolver;
    S3: typeof S3;
    S3ObjectLambda: typeof S3ObjectLambda;
    S3Outposts: typeof S3Outposts;
    SDB: typeof SDB;
    SES: typeof SES;
    SNS: typeof SNS;
    SQS: typeof SQS;
    SSM: typeof SSM;
    SSMContacts: typeof SSMContacts;
    SSMIncidents: typeof SSMIncidents;
    SSO: typeof SSO;
    SageMaker: typeof SageMaker;
    Scheduler: typeof Scheduler;
    SecretsManager: typeof SecretsManager;
    SecurityHub: typeof SecurityHub;
    ServiceCatalog: typeof ServiceCatalog;
    ServiceCatalogAppRegistry: typeof ServiceCatalogAppRegistry;
    ServiceDiscovery: typeof ServiceDiscovery;
    Shield: typeof Shield;
    Signer: typeof Signer;
    StepFunctions: typeof StepFunctions;
    SupportApp: typeof SupportApp;
    Synthetics: typeof Synthetics;
    SystemsManagerSAP: typeof SystemsManagerSAP;
    Timestream: typeof Timestream;
    Transfer: typeof Transfer;
    VerifiedPermissions: typeof VerifiedPermissions;
    VoiceID: typeof VoiceID;
    VpcLattice: typeof VpcLattice;
    WAF: typeof WAF;
    WAFRegional: typeof WAFRegional;
    WAFv2: typeof WAFv2;
    Wisdom: typeof Wisdom;
    WorkSpaces: typeof WorkSpaces;
    WorkSpacesWeb: typeof WorkSpacesWeb;
    XRay: typeof XRay;
    ASK: typeof ASK;
    GroundStation: typeof GroundStation;
    LookoutEquipment: typeof LookoutEquipment;
    CodeTest: typeof CodeTest;
    HealthLake: typeof HealthLake;
    PinpointEmail: typeof PinpointEmail;
    FraudDetector: typeof FraudDetector;
    GammaDilithium: typeof GammaDilithium;
    Omics: typeof Omics;
    Panorama: typeof Panorama;
    SimSpaceWeaver: typeof SimSpaceWeaver;
    ConnectCampaigns: typeof ConnectCampaigns;
    HealthImaging: typeof HealthImaging;
    FinSpace: typeof FinSpace;
    IoTFleetWise: typeof IoTFleetWise;
    BillingConductor: typeof BillingConductor;
    CUR: typeof CUR;
    Route53RecoveryControl: typeof Route53RecoveryControl;
    Route53RecoveryReadiness: typeof Route53RecoveryReadiness;
    DeviceFarm: typeof DeviceFarm;
};
export default _default;
