import XRay from './xRay';
export { XRay };
import EC2 from './ec2';
export { EC2 };
import ACMPCA from './acmpca';
export { ACMPCA };
import ServiceCatalog from './serviceCatalog';
export { ServiceCatalog };
import GlobalAccelerator from './globalAccelerator';
export { GlobalAccelerator };
import AccessAnalyzer from './accessAnalyzer';
export { AccessAnalyzer };
import WAF from './waf';
export { WAF };
import IAM from './iam';
export { IAM };
import WAFRegional from './wafRegional';
export { WAFRegional };
import Backup from './backup';
export { Backup };
import AppIntegrations from './appIntegrations';
export { AppIntegrations };
import Route53Resolver from './route53Resolver';
export { Route53Resolver };
import Elasticsearch from './elasticsearch';
export { Elasticsearch };
import EMR from './emr';
export { EMR };
import WorkSpaces from './workSpaces';
export { WorkSpaces };
import LookoutMetrics from './lookoutMetrics';
export { LookoutMetrics };
import ApiGatewayV2 from './apiGatewayV2';
export { ApiGatewayV2 };
import MediaPackage from './mediaPackage';
export { MediaPackage };
import SageMaker from './sageMaker';
export { SageMaker };
import Kinesis from './kinesis';
export { Kinesis };
import RAM from './ram';
export { RAM };
import AutoScaling from './autoScaling';
export { AutoScaling };
import SQS from './sqs';
export { SQS };
import AppSync from './appSync';
export { AppSync };
import DataSync from './dataSync';
export { DataSync };
import Route53 from './route53';
export { Route53 };
import ManagedBlockchain from './managedBlockchain';
export { ManagedBlockchain };
import CloudWatch from './cloudWatch';
export { CloudWatch };
import ECS from './ecs';
export { ECS };
import StepFunctions from './stepFunctions';
export { StepFunctions };
import NetworkManager from './networkManager';
export { NetworkManager };
import CodeStarConnections from './codeStarConnections';
export { CodeStarConnections };
import CloudFront from './cloudFront';
export { CloudFront };
import KinesisAnalytics from './kinesisAnalytics';
export { KinesisAnalytics };
import CloudFormation from './cloudFormation';
export { CloudFormation };
import Cognito from './cognito';
export { Cognito };
import AppStream from './appStream';
export { AppStream };
import Glue from './glue';
export { Glue };
import Greengrass from './greengrass';
export { Greengrass };
import GuardDuty from './guardDuty';
export { GuardDuty };
import Budgets from './budgets';
export { Budgets };
import LakeFormation from './lakeFormation';
export { LakeFormation };
import S3 from './s3';
export { S3 };
import SNS from './sns';
export { SNS };
import EFS from './efs';
export { EFS };
import MediaConnect from './mediaConnect';
export { MediaConnect };
import QuickSight from './quickSight';
export { QuickSight };
import ApiGateway from './apiGateway';
export { ApiGateway };
import KMS from './kms';
export { KMS };
import Redshift from './redshift';
export { Redshift };
import ApplicationInsights from './applicationInsights';
export { ApplicationInsights };
import CustomerProfiles from './customerProfiles';
export { CustomerProfiles };
import OpsWorks from './opsWorks';
export { OpsWorks };
import EKS from './eks';
export { EKS };
import AppMesh from './appMesh';
export { AppMesh };
import Lambda from './lambda';
export { Lambda };
import CE from './ce';
export { CE };
import IoT1Click from './ioT1Click';
export { IoT1Click };
import IoT from './iot';
export { IoT };
import MediaConvert from './mediaConvert';
export { MediaConvert };
import QLDB from './qldb';
export { QLDB };
import WAFv2 from './waFv2';
export { WAFv2 };
import Batch from './batch';
export { Batch };
import DataBrew from './dataBrew';
export { DataBrew };
import GameLift from './gameLift';
export { GameLift };
import ElastiCache from './elastiCache';
export { ElastiCache };
import RDS from './rds';
export { RDS };
import ElasticLoadBalancing from './elasticLoadBalancing';
export { ElasticLoadBalancing };
import IoTFleetHub from './ioTFleetHub';
export { IoTFleetHub };
import CodeArtifact from './codeArtifact';
export { CodeArtifact };
import MWAA from './mwaa';
export { MWAA };
import Logs from './logs';
export { Logs };
import Macie from './macie';
export { Macie };
import Config from './config';
export { Config };
import SecretsManager from './secretsManager';
export { SecretsManager };
import ElasticLoadBalancingV2 from './elasticLoadBalancingV2';
export { ElasticLoadBalancingV2 };
import CodeBuild from './codeBuild';
export { CodeBuild };
import AmazonMQ from './amazonMq';
export { AmazonMQ };
import DMS from './dms';
export { DMS };
import S3ObjectLambda from './s3ObjectLambda';
export { S3ObjectLambda };
import NetworkFirewall from './networkFirewall';
export { NetworkFirewall };
import Events from './events';
export { Events };
import CodeDeploy from './codeDeploy';
export { CodeDeploy };
import Location from './location';
export { Location };
import DAX from './dax';
export { DAX };
import CloudTrail from './cloudTrail';
export { CloudTrail };
import CodePipeline from './codePipeline';
export { CodePipeline };
import DocDB from './docDb';
export { DocDB };
import ServiceCatalogAppRegistry from './serviceCatalogAppRegistry';
export { ServiceCatalogAppRegistry };
import SSMContacts from './ssmContacts';
export { SSMContacts };
import GreengrassV2 from './greengrassV2';
export { GreengrassV2 };
import RoboMaker from './roboMaker';
export { RoboMaker };
import IoTAnalytics from './ioTAnalytics';
export { IoTAnalytics };
import Amplify from './amplify';
export { Amplify };
import EventSchemas from './eventSchemas';
export { EventSchemas };
import Cloud9 from './cloud9';
export { Cloud9 };
import ServiceDiscovery from './serviceDiscovery';
export { ServiceDiscovery };
import AppConfig from './appConfig';
export { AppConfig };
import FIS from './fis';
export { FIS };
import SSM from './ssm';
export { SSM };
import KinesisAnalyticsV2 from './kinesisAnalyticsV2';
export { KinesisAnalyticsV2 };
import DevOpsGuru from './devOpsGuru';
export { DevOpsGuru };
import AuditManager from './auditManager';
export { AuditManager };
import SSMIncidents from './ssmIncidents';
export { SSMIncidents };
import Detective from './detective';
export { Detective };
import Synthetics from './synthetics';
export { Synthetics };
import DLM from './dlm';
export { DLM };
import SDB from './sdb';
export { SDB };
import IoTEvents from './ioTEvents';
export { IoTEvents };
import ECR from './ecr';
export { ECR };
import S3Outposts from './s3Outposts';
export { S3Outposts };
import FMS from './fms';
export { FMS };
import MediaLive from './mediaLive';
export { MediaLive };
import Transfer from './transfer';
export { Transfer };
import CodeGuruReviewer from './codeGuruReviewer';
export { CodeGuruReviewer };
import ElasticBeanstalk from './elasticBeanstalk';
export { ElasticBeanstalk };
import IoTCoreDeviceAdvisor from './ioTCoreDeviceAdvisor';
export { IoTCoreDeviceAdvisor };
import ImageBuilder from './imageBuilder';
export { ImageBuilder };
import IoTThingsGraph from './ioTThingsGraph';
export { IoTThingsGraph };
import AutoScalingPlans from './autoScalingPlans';
export { AutoScalingPlans };
import SSO from './sso';
export { SSO };
import DirectoryService from './directoryService';
export { DirectoryService };
import LicenseManager from './licenseManager';
export { LicenseManager };
import CertificateManager from './certificateManager';
export { CertificateManager };
import CodeStarNotifications from './codeStarNotifications';
export { CodeStarNotifications };
import Inspector from './inspector';
export { Inspector };
import EMRContainers from './emrContainers';
export { EMRContainers };
import OpsWorksCM from './opsWorksCm';
export { OpsWorksCM };
import AppFlow from './appFlow';
export { AppFlow };
import SecurityHub from './securityHub';
export { SecurityHub };
import FSx from './fSx';
export { FSx };
import DataPipeline from './dataPipeline';
export { DataPipeline };
import Signer from './signer';
export { Signer };
import CodeGuruProfiler from './codeGuruProfiler';
export { CodeGuruProfiler };
import Athena from './athena';
export { Athena };
import ApplicationAutoScaling from './applicationAutoScaling';
export { ApplicationAutoScaling };
import MediaStore from './mediaStore';
export { MediaStore };
import ResourceGroups from './resourceGroups';
export { ResourceGroups };
import LookoutVision from './lookoutVision';
export { LookoutVision };
import KinesisFirehose from './kinesisFirehose';
export { KinesisFirehose };
import MSK from './msk';
export { MSK };
import DynamoDB from './dynamoDb';
export { DynamoDB };
import Cassandra from './cassandra';
export { Cassandra };
import AppRunner from './appRunner';
export { AppRunner };
import CodeStar from './codeStar';
export { CodeStar };
import Chatbot from './chatbot';
export { Chatbot };
import SES from './ses';
export { SES };
import GroundStation from './groundStation';
export { GroundStation };
import ASK from './ask';
export { ASK };
import Pinpoint from './pinpoint';
export { Pinpoint };
import PinpointEmail from './pinpointEmail';
export { PinpointEmail };
import FraudDetector from './fraudDetector';
export { FraudDetector };
import IoTSiteWise from './ioTSiteWise';
export { IoTSiteWise };
import Kendra from './kendra';
export { Kendra };
import Neptune from './neptune';
export { Neptune };
import NimbleStudio from './nimbleStudio';
export { NimbleStudio };
import FinSpace from './finSpace';
export { FinSpace };
import Timestream from './timestream';
export { Timestream };
import IoTWireless from './ioTWireless';
export { IoTWireless };
import IVS from './ivs';
export { IVS };
import CodeCommit from './codeCommit';
export { CodeCommit };
import CUR from './cur';
export { CUR };
declare const _default: {
    XRay: typeof XRay;
    EC2: typeof EC2;
    ACMPCA: typeof ACMPCA;
    ServiceCatalog: typeof ServiceCatalog;
    GlobalAccelerator: typeof GlobalAccelerator;
    AccessAnalyzer: typeof AccessAnalyzer;
    WAF: typeof WAF;
    IAM: typeof IAM;
    WAFRegional: typeof WAFRegional;
    Backup: typeof Backup;
    AppIntegrations: typeof AppIntegrations;
    Route53Resolver: typeof Route53Resolver;
    Elasticsearch: typeof Elasticsearch;
    EMR: typeof EMR;
    WorkSpaces: typeof WorkSpaces;
    LookoutMetrics: typeof LookoutMetrics;
    ApiGatewayV2: typeof ApiGatewayV2;
    MediaPackage: typeof MediaPackage;
    SageMaker: typeof SageMaker;
    Kinesis: typeof Kinesis;
    RAM: typeof RAM;
    AutoScaling: typeof AutoScaling;
    SQS: typeof SQS;
    AppSync: typeof AppSync;
    DataSync: typeof DataSync;
    Route53: typeof Route53;
    ManagedBlockchain: typeof ManagedBlockchain;
    CloudWatch: typeof CloudWatch;
    ECS: typeof ECS;
    StepFunctions: typeof StepFunctions;
    NetworkManager: typeof NetworkManager;
    CodeStarConnections: typeof CodeStarConnections;
    CloudFront: typeof CloudFront;
    KinesisAnalytics: typeof KinesisAnalytics;
    CloudFormation: typeof CloudFormation;
    Cognito: typeof Cognito;
    AppStream: typeof AppStream;
    Glue: typeof Glue;
    Greengrass: typeof Greengrass;
    GuardDuty: typeof GuardDuty;
    Budgets: typeof Budgets;
    LakeFormation: typeof LakeFormation;
    S3: typeof S3;
    SNS: typeof SNS;
    EFS: typeof EFS;
    MediaConnect: typeof MediaConnect;
    QuickSight: typeof QuickSight;
    ApiGateway: typeof ApiGateway;
    KMS: typeof KMS;
    Redshift: typeof Redshift;
    ApplicationInsights: typeof ApplicationInsights;
    CustomerProfiles: typeof CustomerProfiles;
    OpsWorks: typeof OpsWorks;
    EKS: typeof EKS;
    AppMesh: typeof AppMesh;
    Lambda: typeof Lambda;
    CE: typeof CE;
    IoT1Click: typeof IoT1Click;
    IoT: typeof IoT;
    MediaConvert: typeof MediaConvert;
    QLDB: typeof QLDB;
    WAFv2: typeof WAFv2;
    Batch: typeof Batch;
    DataBrew: typeof DataBrew;
    GameLift: typeof GameLift;
    ElastiCache: typeof ElastiCache;
    RDS: typeof RDS;
    ElasticLoadBalancing: typeof ElasticLoadBalancing;
    IoTFleetHub: typeof IoTFleetHub;
    CodeArtifact: typeof CodeArtifact;
    MWAA: typeof MWAA;
    Logs: typeof Logs;
    Macie: typeof Macie;
    Config: typeof Config;
    SecretsManager: typeof SecretsManager;
    ElasticLoadBalancingV2: typeof ElasticLoadBalancingV2;
    CodeBuild: typeof CodeBuild;
    AmazonMQ: typeof AmazonMQ;
    DMS: typeof DMS;
    S3ObjectLambda: typeof S3ObjectLambda;
    NetworkFirewall: typeof NetworkFirewall;
    Events: typeof Events;
    CodeDeploy: typeof CodeDeploy;
    Location: typeof Location;
    DAX: typeof DAX;
    CloudTrail: typeof CloudTrail;
    CodePipeline: typeof CodePipeline;
    DocDB: typeof DocDB;
    ServiceCatalogAppRegistry: typeof ServiceCatalogAppRegistry;
    SSMContacts: typeof SSMContacts;
    GreengrassV2: typeof GreengrassV2;
    RoboMaker: typeof RoboMaker;
    IoTAnalytics: typeof IoTAnalytics;
    Amplify: typeof Amplify;
    EventSchemas: typeof EventSchemas;
    Cloud9: typeof Cloud9;
    ServiceDiscovery: typeof ServiceDiscovery;
    AppConfig: typeof AppConfig;
    FIS: typeof FIS;
    SSM: typeof SSM;
    KinesisAnalyticsV2: typeof KinesisAnalyticsV2;
    DevOpsGuru: typeof DevOpsGuru;
    AuditManager: typeof AuditManager;
    SSMIncidents: typeof SSMIncidents;
    Detective: typeof Detective;
    Synthetics: typeof Synthetics;
    DLM: typeof DLM;
    SDB: typeof SDB;
    IoTEvents: typeof IoTEvents;
    ECR: typeof ECR;
    S3Outposts: typeof S3Outposts;
    FMS: typeof FMS;
    MediaLive: typeof MediaLive;
    Transfer: typeof Transfer;
    CodeGuruReviewer: typeof CodeGuruReviewer;
    ElasticBeanstalk: typeof ElasticBeanstalk;
    IoTCoreDeviceAdvisor: typeof IoTCoreDeviceAdvisor;
    ImageBuilder: typeof ImageBuilder;
    IoTThingsGraph: typeof IoTThingsGraph;
    AutoScalingPlans: typeof AutoScalingPlans;
    SSO: typeof SSO;
    DirectoryService: typeof DirectoryService;
    LicenseManager: typeof LicenseManager;
    CertificateManager: typeof CertificateManager;
    CodeStarNotifications: typeof CodeStarNotifications;
    Inspector: typeof Inspector;
    EMRContainers: typeof EMRContainers;
    OpsWorksCM: typeof OpsWorksCM;
    AppFlow: typeof AppFlow;
    SecurityHub: typeof SecurityHub;
    FSx: typeof FSx;
    DataPipeline: typeof DataPipeline;
    Signer: typeof Signer;
    CodeGuruProfiler: typeof CodeGuruProfiler;
    Athena: typeof Athena;
    ApplicationAutoScaling: typeof ApplicationAutoScaling;
    MediaStore: typeof MediaStore;
    ResourceGroups: typeof ResourceGroups;
    LookoutVision: typeof LookoutVision;
    KinesisFirehose: typeof KinesisFirehose;
    MSK: typeof MSK;
    DynamoDB: typeof DynamoDB;
    Cassandra: typeof Cassandra;
    AppRunner: typeof AppRunner;
    CodeStar: typeof CodeStar;
    Chatbot: typeof Chatbot;
    SES: typeof SES;
    GroundStation: typeof GroundStation;
    ASK: typeof ASK;
    Pinpoint: typeof Pinpoint;
    PinpointEmail: typeof PinpointEmail;
    FraudDetector: typeof FraudDetector;
    IoTSiteWise: typeof IoTSiteWise;
    Kendra: typeof Kendra;
    Neptune: typeof Neptune;
    NimbleStudio: typeof NimbleStudio;
    FinSpace: typeof FinSpace;
    Timestream: typeof Timestream;
    IoTWireless: typeof IoTWireless;
    IVS: typeof IVS;
    CodeCommit: typeof CodeCommit;
    CUR: typeof CUR;
};
export default _default;
