import ElasticBeanstalk from './elasticBeanstalk';
export { ElasticBeanstalk };
import AmazonMQ from './amazonMq';
export { AmazonMQ };
import AppSync from './appSync';
export { AppSync };
import EC2 from './ec2';
export { EC2 };
import ServiceCatalog from './serviceCatalog';
export { ServiceCatalog };
import Cognito from './cognito';
export { Cognito };
import Greengrass from './greengrass';
export { Greengrass };
import Events from './events';
export { Events };
import WAF from './waf';
export { WAF };
import IAM from './iam';
export { IAM };
import CodePipeline from './codePipeline';
export { CodePipeline };
import Elasticsearch from './elasticsearch';
export { Elasticsearch };
import WAFRegional from './wafRegional';
export { WAFRegional };
import ApiGateway from './apiGateway';
export { ApiGateway };
import EMR from './emr';
export { EMR };
import WorkSpaces from './workSpaces';
export { WorkSpaces };
import RDS from './rds';
export { RDS };
import ApiGatewayV2 from './apiGatewayV2';
export { ApiGatewayV2 };
import Logs from './logs';
export { Logs };
import RAM from './ram';
export { RAM };
import Kinesis from './kinesis';
export { Kinesis };
import AutoScaling from './autoScaling';
export { AutoScaling };
import SQS from './sqs';
export { SQS };
import AutoScalingPlans from './autoScalingPlans';
export { AutoScalingPlans };
import AppStream from './appStream';
export { AppStream };
import Route53 from './route53';
export { Route53 };
import CloudWatch from './cloudWatch';
export { CloudWatch };
import ECS from './ecs';
export { ECS };
import ElasticLoadBalancingV2 from './elasticLoadBalancingV2';
export { ElasticLoadBalancingV2 };
import StepFunctions from './stepFunctions';
export { StepFunctions };
import OpsWorks from './opsWorks';
export { OpsWorks };
import CloudFront from './cloudFront';
export { CloudFront };
import GameLift from './gameLift';
export { GameLift };
import GuardDuty from './guardDuty';
export { GuardDuty };
import DirectoryService from './directoryService';
export { DirectoryService };
import SNS from './sns';
export { SNS };
import EFS from './efs';
export { EFS };
import SSM from './ssm';
export { SSM };
import Config from './config';
export { Config };
import SageMaker from './sageMaker';
export { SageMaker };
import KMS from './kms';
export { KMS };
import Redshift from './redshift';
export { Redshift };
import Lambda from './lambda';
export { Lambda };
import CertificateManager from './certificateManager';
export { CertificateManager };
import Inspector from './inspector';
export { Inspector };
import IoT1Click from './ioT1Click';
export { IoT1Click };
import IoTAnalytics from './ioTAnalytics';
export { IoTAnalytics };
import Batch from './batch';
export { Batch };
import OpsWorksCM from './opsWorksCm';
export { OpsWorksCM };
import ElasticLoadBalancing from './elasticLoadBalancing';
export { ElasticLoadBalancing };
import IoT from './iot';
export { IoT };
import DMS from './dms';
export { DMS };
import Glue from './glue';
export { Glue };
import ElastiCache from './elastiCache';
export { ElastiCache };
import CodeDeploy from './codeDeploy';
export { CodeDeploy };
import SecretsManager from './secretsManager';
export { SecretsManager };
import CodeBuild from './codeBuild';
export { CodeBuild };
import Budgets from './budgets';
export { Budgets };
import DAX from './dax';
export { DAX };
import DataPipeline from './dataPipeline';
export { DataPipeline };
import Route53Resolver from './route53Resolver';
export { Route53Resolver };
import CloudTrail from './cloudTrail';
export { CloudTrail };
import CloudFormation from './cloudFormation';
export { CloudFormation };
import ServiceDiscovery from './serviceDiscovery';
export { ServiceDiscovery };
import ApplicationAutoScaling from './applicationAutoScaling';
export { ApplicationAutoScaling };
import S3 from './s3';
export { S3 };
import KinesisFirehose from './kinesisFirehose';
export { KinesisFirehose };
import DLM from './dlm';
export { DLM };
import SDB from './sdb';
export { SDB };
import ECR from './ecr';
export { ECR };
import DynamoDB from './dynamoDb';
export { DynamoDB };
import Athena from './athena';
export { Athena };
import ASK from './ask';
export { ASK };
import Cloud9 from './cloud9';
export { Cloud9 };
import Neptune from './neptune';
export { Neptune };
import DocDB from './docDb';
export { DocDB };
import KinesisAnalytics from './kinesisAnalytics';
export { KinesisAnalytics };
import SES from './ses';
export { SES };
import FSx from './fSx';
export { FSx };
import RoboMaker from './roboMaker';
export { RoboMaker };
import KinesisAnalyticsV2 from './kinesisAnalyticsV2';
export { KinesisAnalyticsV2 };
import CodeCommit from './codeCommit';
export { CodeCommit };
import EKS from './eks';
export { EKS };
declare const _default: {
    ElasticBeanstalk: typeof ElasticBeanstalk;
    AmazonMQ: typeof AmazonMQ;
    AppSync: typeof AppSync;
    EC2: typeof EC2;
    ServiceCatalog: typeof ServiceCatalog;
    Cognito: typeof Cognito;
    Greengrass: typeof Greengrass;
    Events: typeof Events;
    WAF: typeof WAF;
    IAM: typeof IAM;
    CodePipeline: typeof CodePipeline;
    Elasticsearch: typeof Elasticsearch;
    WAFRegional: typeof WAFRegional;
    ApiGateway: typeof ApiGateway;
    EMR: typeof EMR;
    WorkSpaces: typeof WorkSpaces;
    RDS: typeof RDS;
    ApiGatewayV2: typeof ApiGatewayV2;
    Logs: typeof Logs;
    RAM: typeof RAM;
    Kinesis: typeof Kinesis;
    AutoScaling: typeof AutoScaling;
    SQS: typeof SQS;
    AutoScalingPlans: typeof AutoScalingPlans;
    AppStream: typeof AppStream;
    Route53: typeof Route53;
    CloudWatch: typeof CloudWatch;
    ECS: typeof ECS;
    ElasticLoadBalancingV2: typeof ElasticLoadBalancingV2;
    StepFunctions: typeof StepFunctions;
    OpsWorks: typeof OpsWorks;
    CloudFront: typeof CloudFront;
    GameLift: typeof GameLift;
    GuardDuty: typeof GuardDuty;
    DirectoryService: typeof DirectoryService;
    SNS: typeof SNS;
    EFS: typeof EFS;
    SSM: typeof SSM;
    Config: typeof Config;
    SageMaker: typeof SageMaker;
    KMS: typeof KMS;
    Redshift: typeof Redshift;
    Lambda: typeof Lambda;
    CertificateManager: typeof CertificateManager;
    Inspector: typeof Inspector;
    IoT1Click: typeof IoT1Click;
    IoTAnalytics: typeof IoTAnalytics;
    Batch: typeof Batch;
    OpsWorksCM: typeof OpsWorksCM;
    ElasticLoadBalancing: typeof ElasticLoadBalancing;
    IoT: typeof IoT;
    DMS: typeof DMS;
    Glue: typeof Glue;
    ElastiCache: typeof ElastiCache;
    CodeDeploy: typeof CodeDeploy;
    SecretsManager: typeof SecretsManager;
    CodeBuild: typeof CodeBuild;
    Budgets: typeof Budgets;
    DAX: typeof DAX;
    DataPipeline: typeof DataPipeline;
    Route53Resolver: typeof Route53Resolver;
    CloudTrail: typeof CloudTrail;
    CloudFormation: typeof CloudFormation;
    ServiceDiscovery: typeof ServiceDiscovery;
    ApplicationAutoScaling: typeof ApplicationAutoScaling;
    S3: typeof S3;
    KinesisFirehose: typeof KinesisFirehose;
    DLM: typeof DLM;
    SDB: typeof SDB;
    ECR: typeof ECR;
    DynamoDB: typeof DynamoDB;
    Athena: typeof Athena;
    ASK: typeof ASK;
    Cloud9: typeof Cloud9;
    Neptune: typeof Neptune;
    DocDB: typeof DocDB;
    KinesisAnalytics: typeof KinesisAnalytics;
    SES: typeof SES;
    FSx: typeof FSx;
    RoboMaker: typeof RoboMaker;
    KinesisAnalyticsV2: typeof KinesisAnalyticsV2;
    CodeCommit: typeof CodeCommit;
    EKS: typeof EKS;
};
export default _default;
