"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.URLSuffix = exports.StackName = exports.StackId = exports.Region = exports.Partition = exports.NoValue = exports.NotificationARNs = exports.AccountId = void 0;
const functions_1 = require("./functions");
exports.AccountId = (0, functions_1.Ref)('AWS::AccountId');
exports.NotificationARNs = (0, functions_1.Ref)("AWS::NotificationARNs");
exports.NoValue = (0, functions_1.Ref)('AWS::NoValue');
exports.Partition = (0, functions_1.Ref)('AWS::Partition');
exports.Region = (0, functions_1.Ref)('AWS::Region');
exports.StackId = (0, functions_1.Ref)('AWS::StackId');
exports.StackName = (0, functions_1.Ref)('AWS::StackName');
exports.URLSuffix = (0, functions_1.Ref)('AWS::URLSuffix');
